### ISSUE TITLE
Who is responsible for the Vegetable Growing Area?

### ISSUE THREAD

**Issue by nelsonic** [mosteirodelandim/site#4]
Since the old land caretakers left last year, the area that was a thriving vegetable garden has been virtually empty. 😕 
Only a handful of tomatoes were grown on almost **`1 Acre`** of land: 

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/194400/188837501-fa38a278-8f46-4e1c-872b-b7c675a5b8ab.png">

We visited last Sunday at end of the main growing season and it was _empty_:

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/194400/188837623-22d98488-1108-46af-96b4-483f6db347c4.png">

Is this deliberate? Are they leaving the land [fallow](https://en.wikipedia.org/wiki/Fallow) to let it "rest", 💤 
(in which case, why weren't nitrogen-fixing chop-and-drop plants planted to maximise soil improvement ...?)
or was there just "_not enough **time**_" to manage the vegetable patch this year? ⏳ 

Who is responsible for this part of the land? 🤷‍♂️ 
If nobody is going to grow anything on it, could we plant a few vegetables 🥦 
that _everyone_ in the family could benefit from? 🥗 

At the current [extortionate] price of most vegetables, this small patch of land could _easily_ yield **`€2k+/year`** 💰 
in higher-value annual cash crops like broccoli, kale, squash and ginger. 🥬

**Comment by iteles** [comment]
This isn't a `site` issue. Looks like we need a new repo for admin tasks.

At the moment, the owners of the farm are responsible for it.

We _could_ I'm sure plant a few vegetables on it but that would require regular upkeep _from us_ (rather than delegated because the farm hands have a lot on right now) and I'm not convinced we have the time to dedicate to is right now ⏳ 🌲 

Broccoli goes to seed pretty quickly but some squash are pretty low maintenance...

**Comment by nelsonic** [comment]
Sorry, I thought that "site" meant "on site" 
as there is a **website** repo: https://github.com/mosteirodelandim/landim-website 
that makes sense for website related issues ...

Question remains tho ... ❓ 

Who is _responsible_? 🤷‍♂️ 
i.e. who would we need to get _permission_ from 👩  
to _invest_ in automated [low-water-use] drip irrigation (**`€300`**) 💧 
to plant **`€2k/year`** worth of vegetables. 🥦 
I'd _very_ gladly visit once every two weeks to tend to crops (even in the rain) 📆 
if it meant that I got **_unlimited_ vegetables** many of which we could sell on. 💵 
We already have all the seeds. Just need the _land_. 👨‍🌾 

Feel free to migrate this issue to the more appropriate repo. 👍

**Comment by iteles** [comment]
> At the moment, the owners of the farm are responsible for it.

These are the people you need buy-in from.

I suggest you need to know exactly where the water source is and how much work it would be to install the system before we bring it up with them.

If only there was wifi so we could keep an eye on it remotely 🤔

**Comment by nelsonic** [comment]
@iteles / @LuchoTurtle was the WIFI in the casa dos caseiros cancelled after they left? 🤷‍♂️ 

I'd very happily pay **`€10/month`** for a [**`WOO`**](https://www.woo.pt/tarifarios-telemovel) 4G SIM with **`4Gb`** to send updates 📶 
e.g: a couple of still images per day + soil moisture, sun index and temperature data 📷 
We could capture _way_ more images and then time-lapse them 
but only _send_ a handful per day to conserve bandwidth. 

https://www.google.com/search?q=12+megapixel+image+size+mb
<img width="534" alt="image" src="https://user-images.githubusercontent.com/194400/189145547-07cbd9ce-b431-4ae7-9b44-21724c7214d9.png">

https://www.google.com/search?q=4+gigabytes+divided+by+3.2+mb
<img width="437" alt="image" src="https://user-images.githubusercontent.com/194400/189145677-a4eb0066-0569-4397-806e-bf374c5d1853.png">

1250 images per month 
1250 / 30 = 42 images per day.
If we assume there are **`16h`** of light per day, 
It's 2.6 images per hour.
This also works well for the time lapse 
because it would basically be just under 2 seconds of footage per day
which would result in a 12 minute time lapse video over 365 days.

**Comment by LuchoTurtle** [comment]
@nelsonic @iteles I asked Tia R if anyone was using it and apparently Ricardo is starting just recently to use it (he was super busy with a myriad of stuff). So it's basically his, I wager.

About the wifi, Zé paid for it. Ever since he left, there's nothing there right now, so no interwebs we can use ☹️

**Comment by nelsonic** [comment]
@LuchoTurtle coolio. 👌 
Makes sense for Ricardo to have the area for his personal growing. 🥬 
Thanks for confirming. ✅
